packageExtensions:
  "react-frame-component@*":
    dependencies:
      "prop-types": "*"
  "react-table@*":
    dependencies:
      "prop-types": "*"
  "react-redux@*":
    dependencies:
      "react-dom": "*"
  "react-router-config@*":
    dependencies:
      "react-router": "*"
  "material-table@*":
    dependencies:
      "@babel/runtime": "*"
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
      "@firebase/util": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@material-ui/pickers@*":
    dependencies:
      "@material-ui/styles": "*"
  "react-event-listener@*":
    dependencies:
      "react": "*"
  "eslint-config-react-app@*":
    peerDependencies:
      "eslint-plugin-flowtype": "*"

